version: "3.1"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  shopping-list-backend:
    image: shopping-list-backend:latest
    container_name: shopping-list-backend
    restart: always
    environment:
      PORT: 5000
      CLIENT_URL: http://127.0.0.1:80
      MONGO_URL: ${MONGO_URL}

  shopping-list-frontend:
    image: shopping-list-frontend:latest
    container_name: shopping-list-frontend
    restart: always
    environment:
      REACT_APP_BACKEND: /api
